permalink: /:title

# Meta
title:                  Meet The Canelakes
tagline:                Canelake Family
aboutme:                
url:                    https://canelake.com
baseurl:                /
author:
  name:                 Sarina Canelake
  url:                  https://twitter.com/robotsari
  email:                sarina@canelake.com

# Custom vars
resume:                  resume/resume--sarina-canelake-2020.pdf
